### ISSUE TITLE
tests fail on windows - reopening the closed issue

### ISSUE THREAD

**Issue by creditquant** [KxSystems/embedPy#76]
I seem to be running into an issue that was reported here in July 2018 and closed - but am still getting the same symptoms working with the latest embedPy (release 1.3.2).

Below is the relevant excerpt:

(base) D:\temp\embedPy>conda install --file tests/requirements.txt
Collecting package metadata: done
Solving environment: done

All requested packages already installed.

(base) D:\temp\embedPy>q test.q
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
w64/ 4(16)core 8109MB Tahsin Alam hunter 10.0.75.1 EXPIRE 2020.04.13 alam.tahsin@gmail.com KOD #4164452

WARN: can't import: resource, remainder of tests/memory.t skipped, error was:

        import: No module named 'resource'

WARNING:tensorflow:From d:\bin\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-28 17:38:26.237259: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-28 17:38:26.248395: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
These modules required for tests couldn't be imported:
        resource

try running
        pip install -r tests/requirements.txt

or with conda
        conda install --file tests/requirements.txt

failed:0, errored:0, skipped:16, total:273

(base) D:\temp\embedPy>q
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
w64/ 4(16)core 8109MB Tahsin Alam hunter 10.0.75.1 EXPIRE 2020.04.13 alam.tahsin@gmail.com KOD #4164452

q)\\

(base) D:\temp\embedPy>python --version
Python 3.6.8 :: Anaconda custom (64-bit)

**Comment by cmccarthy1** [comment]
Hi

The issue you're seeing isn't actually an error. For the windows install there is no available package `resource`. As such we test to see if it is possible to import the package (which it would not be in windows and return the warning you're seeing with the message that the associated tests have been skipped)

In regards to the tensorflow warnings that's likely due to the version of tensorflow being used but it's not causing any issues...

The main area to take note of is the line `failed:0, errored:0, skipped:16, total:273` which indicates that based on our tests your embedPy install is working correctly.

I'm going to close this issue for now, let me know if there are any more problems.
