### ISSUE TITLE
tensorflow.t 

### ISSUE THREAD

**Issue by swat-agarwal** [KxSystems/embedPy#85]
I am getting the below error

ERROR:
 test:
  1 3~raze"j"$10*fit[x;y]
 message:
  call: module 'tensorflow' has no attribute 'random_uniform'
    [11] 1 3~raze"j"$10*fit[x;y]
                        ^
 file:
  tests/tensorflow.t

failed:0, errored:4, skipped:16, total:273

**Comment by cmccarthy1** [comment]
Where did you source the version of embedPy from and when?

Pull request #82 in January should have checks for this issue in place on the master branch of the GitHub repo.

Errors are a result from a deprecation resulting from version change of tensorflow rather than an issue with embedPy.

The *.t scripts are largely used for internal testing with travis and appveyor which are public facing and viewable via the tags at the top of our README.

**Comment by swat-agarwal** [comment]
I downloaded from the release page 
https://github.com/KxSystems/embedPy/releases/tag/1.3.2
just yeaterday the windows version

**Comment by cmccarthy1** [comment]
Updated release below should fix the above tensorflow issue
 
https://github.com/KxSystems/embedPy/releases/tag/1.3.3

Please reopen the issue if this is still failing

**Comment by swat-agarwal** [comment]
Now i get the below issue
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003a70 (most recent call first):
